open_canvas/urls.py
from django.urls import path

from .views import CourseDetailView, CourseListView, UserDetailView, UserListView

urlpatterns = [
    path("users/", UserListView.as_view(), name="user-list"),
    path("user/<slug>", UserDetailView.as_view(), name="user-detail"),
    path("courses/", CourseListView.as_view(), name="course-list"),
    path("course/<int:pk>", CourseDetailView.as_view(), name="course-detail"),
]

open_canvas_admin_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("open_canvas.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

open_canvas/models.py
from operator import attrgetter

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db.models import (
    CASCADE,
    CharField,
    EmailField,
    ForeignKey,
    IntegerField,
    ManyToManyField,
    Model,
)

from open_canvas.canvas.api import get_canvas
from open_canvas.canvas.users import get_first_and_last_names, get_user_by_email

UNPUBLISHED = "UNPUBLISHED"
AVAILABLE = "AVAILABLE"
COMPLETED = "COMPLETED"
DELETED = "DELETED"
WORKFLOW_STATES = [
    (UNPUBLISHED, "unpublished"),
    (AVAILABLE, "available"),
    (COMPLETED, "completed"),
    (DELETED, "deleted"),
]


class Course(Model):
    canvas_id = IntegerField(primary_key=True)
    name = CharField(max_length=255)
    course_code = CharField(max_length=255, blank=True, null=True)
    workflow_state = CharField(
        max_length=11, choices=WORKFLOW_STATES, blank=True, null=True
    )
    course_section = ForeignKey(
        "self", on_delete=CASCADE, blank=True, null=True, related_name="course"
    )

    def __str__(self):
        course_code = f"{self.course_code} " if self.course_code else ""
        return f'{course_code}"{self.name}" ({self.canvas_id})'


class Enrollment(Model):
    STUDENT = "STUDENT"
    STUDENT_VIEW = "STUDENT_VIEW"
    TEACHER = "TEACHER"
    TA = "TA"
    DESIGNER = "DESIGNER"
    OBSERVER = "OBSERVER"
    ROLES = [
        (STUDENT, "StudentEnrollment"),
        (STUDENT_VIEW, "StudentViewEnrollment"),
        (TEACHER, "TeacherEnrollment"),
        (TA, "TaEnrollment"),
        (DESIGNER, "DesignerEnrollment"),
        (OBSERVER, "ObserverEnrollment"),
    ]
    course = ManyToManyField(Course)
    course_section = ForeignKey(
        Course, on_delete=CASCADE, blank=True, null=True, related_name="section"
    )
    user = ForeignKey("CanvasUser", on_delete=CASCADE)
    role = CharField(max_length=21, choices=ROLES)


def get_login_type(login_id):
    try:
        validate_email(login_id)
        return CanvasUser.EMAIL
    except ValidationError:
        return CanvasUser.PENN_PATH


class CanvasUser(Model):
    PENN_PATH = "PENNPATH"
    EMAIL = "EMAIL"
    LOGIN_TYPES = [(PENN_PATH, "PennPath"), (EMAIL, "email")]
    first_name = CharField(max_length=255)
    last_name = CharField(max_length=255)
    email = EmailField(primary_key=True)
    penn_key = CharField(max_length=255, unique=True, blank=True, null=True)
    canvas_id = IntegerField(unique=True)
    enrollments = ManyToManyField(Enrollment, related_name="users", blank=True)
    login_type = CharField(max_length=8, choices=LOGIN_TYPES, default=EMAIL)

    def __str__(self):
        return f"{self.full_name} ({self.email})"

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def sortable_name(self):
        return f"{self.last_name}, {self.first_name}"

    @property
    def login_id(self):
        return self.penn_key if self.login_type == self.PENN_PATH else self.email

    def sync_with_canvas(self):
        user = get_canvas().get_user(get_user_by_email(self.email))
        canvas_id, name, login_id = attrgetter("id", "name", "login_id")(user)
        self.canvas_id = canvas_id
        if name != self.full_name:
            first_name, last_name = get_first_and_last_names(name)
            self.first_name = first_name
            self.last_name = last_name
        self.login_type = get_login_type(login_id)
        self.save()

open_canvas/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import CanvasUser, Course


class UserDetailView(DetailView):
    model = CanvasUser
    context_object_name = "user"
    slug_field = "canvas_id"
    template_name = "user_detail.html"


class UserListView(ListView):
    model = CanvasUser
    context_object_name = "users"
    paginate_by = 100
    template_name = "user_list.html"


class CourseDetailView(DetailView):
    model = Course
    template_name = "course_detail.html"


class CourseListView(ListView):
    model = Course
    context_object_name = "courses"
    paginate_by = 100
    template_name = "course_list.html"

open_canvas/templates/canvassite_detail.html
{% extends "base.html" %}
{% block content %}
    <ul class="px-20 py-8">
        {% include "canvassite.html" with site=site %}
    </ul>
{% endblock %}

open_canvas/templates/canvasuser.html
{% url 'user-list' as user_list %}

<li {% if user_list in request.path %} class="py-4" {% endif %}>
    <h3
        {% if user_list not in request.path %}
            class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800"
        {% endif %}
    >
        <a href="{% url "user-detail" user.canvas_id %}" class="underline">
            {{ user.full_name }}
        </a>
    </h3>
    <ul class="px-8 py-4">
        <li>First name: {{ user.first_name }}</li>
        <li>Last name: {{ user.last_name }}</li>
        <li>Full name: {{ user.full_name }}</li>
        <li>Sortable name: {{ user.sortable_name }}</li>
        <li>Email: {{ user.email }}</li>
        <li>Penn ID: {{ user.penn_id }}</li>
        <li>Pennkey: {{ user.penn_key }}</li>
        <li>
            Courses:
            {% if user.courses.all %}
                <ul class="px-8">
                    {% for course in user.courses.all %}
                        <a href="{% url "course-detail" course.canvas_id %}" class="underline">
                            <li>{{ course }}</li>
                        </a>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    </ul>
</li>

open_canvas/templates/canvasuser_detail.html
{% extends "base.html" %}
{% block content %}
    <ul class="px-20 py-8">
        {% include "canvasuser.html" with user=user %}
    </ul>
{% endblock %}

open_canvas/templates/canvasuser_list.html
{% extends "base.html" %}
{% block content %}
    <div class="flex flex-col px-20 py-8">
        <h3 class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800">Canvas Users</h3>
        <ul>
            {% for user in users %}
                {% include "canvasuser.html" with user=user %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}

open_canvas/templates/course.html
{% url 'course-list' as course_list %}

<li {% if course_list in request.path %} class="py-4" {% endif %}>
    <h3
        {% if course_list not in request.path %}
            class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800"
        {% endif %}
    >
        <a href="{% url "course-detail" course.canvas_id %}" class="underline">
            {{ course.name }}
        </a>
    </h3>
    <ul class="px-8 py-4">
        <li>Canvas ID: {{ course.canvas_id }}</li>
        <li>Name: {{ course.name }}</li>
        <li>Course code: {{ course.course_code }}</li>
        <li>Workflow state: {{ course.workflow_state }}</li>
        <li>
            Enrollments:
            {% if course.enrollment_set.all %}
                <ul class="px-8">
                    {% for enrollment in course.enrollment_set.all %}
                        <a href="{% url "user-detail" enrollment.user.canvas_id %}" class="underline">
                            <li>{{ enrollment.user }}</li>
                        </a>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    </ul>
</li>

open_canvas/templates/course_detail.html
{% extends "base.html" %}
{% block content %}
    <ul class="px-20 py-8">
        {% include "course.html" with course=course %}
    </ul>
{% endblock %}

open_canvas/templates/course_list.html
{% extends "base.html" %}
{% block content %}
    <div class="flex flex-col px-20 py-8">
        <h3 class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800">Courses</h3>
        <ul>
            {% for course in courses %}
                {% include "course.html" with course=course %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}

open_canvas/templates/sidenav.html
{% url 'user-list' as users %}
{% url 'course-list' as courses %}

<div
    class="sidenav"
>
    <h2 class="text-3xl font-semibold text-gray-800 dark:text-white text-center">
        Open Canvas
    </h2>
    <div class="flex flex-col justify-between flex-1 mt-6">
        <nav>
            <a
                class="navlink
                       {% if request.path == users %}
                       active
                       {% else %}
                       inactive
                       {% endif %}
                       "
                href={{ users }}
            >
                <span class="mx-4 font-medium">Users</span>
            </a>
            <a
                class="
                       navlink
                       {% if request.path == courses %}
                       active
                       {% else %}
                       inactive
                       {% endif %}
                       "
                href={{ courses }}
            >
                <span class="mx-4 font-medium">Courses</span>
            </a>
        </nav>
    </div>
</div>

open_canvas/templates/user.html
{% url 'user-list' as user_list %}

<li {% if user_list in request.path %} class="py-4" {% endif %}>
    <h3
        {% if user_list not in request.path %}
            class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800"
        {% endif %}
    >
        <a href="{% url "user-detail" user.canvas_id %}" class="underline">
            {{ user.full_name }}
        </a>
    </h3>
    <ul class="px-8 py-4">
        <li>First name: {{ user.first_name }}</li>
        <li>Last name: {{ user.last_name }}</li>
        <li>Full name: {{ user.full_name }}</li>
        <li>Sortable name: {{ user.sortable_name }}</li>
        <li>Email: {{ user.email }}</li>
        <li>Pennkey: {{ user.penn_key }}</li>
        <li>Login Type: {{ user.login_type }}</li>
        <li>
            Enrollments:
            {% if user.enrollment_set.all %}
                <ul class="px-8">
                    {% for enrollment in user.enrollment_set.all %}
                        <a href="{% url "course-detail" enrollment.course.first.canvas_id %}" class="underline">
                            <li>{{ enrollment.course.first }}</li>
                        </a>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    </ul>
</li>

open_canvas/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
    <ul class="px-20 py-8">
        {% include "user.html" with user=user %}
    </ul>
{% endblock %}

open_canvas/templates/user_list.html
{% extends "base.html" %}
{% block content %}
    <div class="flex flex-col px-20 py-8">
        <h3 class="text-4xl font-medium leading-tight mt-0 mb-2 text-gray-800">Users</h3>
        <ul>
            {% for user in users %}
                {% include "user.html" with user=user %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>UPenn Open Canvas User Admin</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal flex">
		{% include "sidenav.html" %}
		{% block content %}
		{% endblock %}
	</body>
</html>